# Generated by Django 4.1.3 on 2025-01-16 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muscleinfo', '0002_exercicio_residual_exercicio_series'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercicio',
            name='residual',
        ),
        migrations.AddField(
            model_name='exercicio',
            name='musculo_residual',
            field=models.CharField(default='', max_length=100),
        ),
    ]
