# Generated by Django 5.1.5 on 2025-01-21 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muscleinfo', '0003_remove_exercicio_residual_exercicio_musculo_residual'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercicio',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
