# Generated by Django 4.2.19 on 2025-02-21 20:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muscleinfo', '0004_exercicio_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercicio',
            name='carga',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exercicio',
            name='carga_anterior',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exercicio',
            name='data',
            field=models.DateField(default=datetime.datetime(2025, 2, 21, 20, 17, 10, 396368, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='exercicio',
            name='data_anterior',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercicio',
            name='repeticoes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exercicio',
            name='repeticoes_anterior',
            field=models.IntegerField(default=0),
        ),
    ]
