# Generated by Django 5.1.6 on 2025-03-04 19:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muscleinfo', '0005_exercicio_carga_exercicio_carga_anterior_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicio',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
