# Generated by Django 5.1.6 on 2025-03-20 19:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muscleinfo', '0006_alter_exercicio_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicio',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='data_anterior',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
