# Generated by Django 4.2.20 on 2025-05-23 14:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('muscleinfo', '0007_alter_exercicio_data_alter_exercicio_data_anterior'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercicio',
            options={'verbose_name_plural': 'Exercícios'},
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='carga',
            field=models.IntegerField(default=0, help_text='Carga utilizada.', verbose_name='Carga utilizada'),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='carga_anterior',
            field=models.IntegerField(default=0, help_text='Carga utilizada anteriormente.', verbose_name='Carga utilizada anteriormente'),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Data do exercício.', verbose_name='Data do exercício'),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='data_anterior',
            field=models.DateTimeField(blank=True, help_text='Data do exercício anterior.', null=True, verbose_name='Data do exercício anterior'),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='musculo',
            field=models.CharField(help_text='Músculo.', max_length=100, verbose_name='Músculo'),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='musculo_residual',
            field=models.CharField(default='', help_text='Músculo residual.', max_length=100, verbose_name='Músculo residual'),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='nome',
            field=models.CharField(help_text='Nome do exercício.', max_length=100, verbose_name='Nome do exercício'),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='repeticoes',
            field=models.IntegerField(default=0, help_text='Número de repetições.', verbose_name='Número de repetições'),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='repeticoes_anterior',
            field=models.IntegerField(default=0, help_text='Número de repetições anterior.', verbose_name='Número de repetições anterior'),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='series',
            field=models.IntegerField(default=0, help_text='Número de séries.', verbose_name='Número de séries'),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='user_id',
            field=models.IntegerField(default=0, help_text='ID do usuário.', verbose_name='ID do usuário'),
        ),
    ]
